# Generated by Django 4.1.5 on 2023-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='hashrate_no_code',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
