# Generated by Django 4.1.5 on 2023-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_asics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ManyToManyField(to='main.cryptocoin')),
            ],
        ),
    ]
