# Generated by Django 4.1.5 on 2023-06-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_duals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duals',
            old_name='first',
            new_name='pair',
        ),
    ]
